name = "v1"
uuid = "16202f79-f0b3-4048-a0d2-7ecb0e04bfdb"
authors = ["mmcmanus1 <mattmcmanus41@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"
HashCode2014 = "0.1.0""

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"

[targets]
test = ["Test", "HashCode2014"]
